/**
 * Visualizer Types
 * Consolidated types for the visualizer application
 */

// Settings types
export type {
  LightAdjustments,
  ColorAdjustments,
  EffectsAdjustments,
  PostAdjustments,
  FlowGenerationSettings,
  VideoPromptSettings,
  VideoGenerationSettings,
  VideoResolution,
  VideoAspectRatio,
  PromptSettings,
  PromptTags,
  AIModelConfig,
  CommerceProvider,
  CommerceConfig,
  ClientMetadata,
  FlowStatus,
  ImageQuality,
  // New types for studio settings redesign
  NativeSceneCategory,
  InputCameraAngle,
  SubjectAnalysis,
  VisionAnalysisJson,
  VisionAnalysisResult,
  InspirationSourceType,
  InspirationImage,
  SceneTypeInspiration,
  SceneTypeInspirationMap,
  StylePreset,
  LightingPreset,
} from './settings';

export {
  DEFAULT_POST_ADJUSTMENTS,
  DEFAULT_FLOW_SETTINGS,
  DEFAULT_PROMPT_SETTINGS,
  DEFAULT_PROMPT_TAGS,
  PROMPT_TAG_OPTIONS,
  VIDEO_TYPE_OPTIONS,
  CAMERA_MOTION_OPTIONS,
  VIDEO_ASPECT_RATIO_OPTIONS,
  VIDEO_RESOLUTION_OPTIONS,
  // New presets for studio settings
  STYLE_PRESETS,
  LIGHTING_PRESETS,
  // Utility functions
  normalizeImageQuality,
} from './settings';

// Message types
export type {
  MessagePartType,
  TextMessagePart,
  ImageMessagePart,
  PromptSettingsMessagePart,
  MessagePart,
  MessageRole,
  GenerationStatus,
} from './messages';

// Domain entity types
export type {
  BaseEntity,
  VersionedEntity,
  User,
  Client,
  Member,
  Product,
  ProductSource,
  ProductAnalysis,
  ProductImage,
  ChatSession,
  CollectionSession,
  CollectionSessionStatus,
  Message,
  GenerationFlow,
  GenerationFlowProduct,
  GeneratedAsset,
  AssetType,
  AssetStatus,
  ApprovalStatus,
  AssetAnalysis,
  GeneratedAssetProduct,
  FavoriteImage,
  StoreConnection,
  StoreType,
  StoreConnectionStatus,
  StoreSyncLog,
  SyncAction,
  SyncStatus,
  GenerationEvent,
  GenerationEventType,
  ProductWithImages,
  ProductWithDetails,
  ChatSessionWithMessages,
  CollectionSessionWithFlows,
  GenerationFlowWithAssets,
  FlowGeneratedImage,
} from './domain';

// Queue types (for scenergy-queue)
export type {
  AIJobType,
  JobStatus,
  JobPriority,
  BaseJobPayload,
  ImageGenerationPayload,
  ImageGenerationSettings,
  ImageEditPayload,
  VideoGenerationPayload,
  UpscalePayload,
  BackgroundRemovalPayload,
  JobPayloadMap,
  JobPayload,
  BaseJobResult,
  ImageGenerationResult,
  ImageEditResult,
  VideoGenerationResult,
  UpscaleResult,
  BackgroundRemovalResult,
  JobResultMap,
  JobResult,
  JobInfo,
  EnqueueOptions,
  QueueStats,
  QueueClientConfig,
  WorkerConfig,
} from './queue';

export { JOB_PRIORITIES } from './queue';

// Database operation types
export type {
  ClientCreate,
  ClientUpdate,
  ProductCreate,
  ProductUpdate,
  ProductImageCreate,
  ProductImageUpdate,
  ChatSessionCreate,
  ChatSessionUpdate,
  CollectionSessionCreate,
  CollectionSessionUpdate,
  MessageCreate,
  MessageUpdate,
  GenerationFlowCreate,
  GenerationFlowUpdate,
  GeneratedAssetCreate,
  GeneratedAssetUpdate,
  GeneratedAssetProductCreate,
  FavoriteImageCreate,
  StoreConnectionCreate,
  StoreConnectionUpdate,
  StoreSyncLogCreate,
  StoreSyncLogUpdate,
  GenerationEventCreate,
  MemberCreate,
  MemberUpdate,
  SessionType,
} from './database';
