import type { FlowGenerationSettings } from 'visualizer-types';

/**
 * Resolve the prompt to use for generation.
 * In the new system, prompts are generated by the Art Director API.
 * This function provides a simple fallback for basic prompt construction.
 */
export function resolvePrompt(settings: FlowGenerationSettings): string {
  // If user provided additional prompt, use it as a base
  if (settings.userPrompt?.trim()) {
    return buildPromptFromSettings(settings);
  }

  return buildPromptFromSettings(settings);
}

/**
 * Build a simple prompt from settings.
 * Note: In the new architecture, the Art Director API handles complex prompt construction
 * using Vision Scanner analysis and Subject Scanner data.
 */
export function buildPromptFromSettings(settings: FlowGenerationSettings): string {
  const parts: string[] = [];

  // Aspect ratio
  if (settings.aspectRatio) {
    parts.push(`Aspect ratio: ${settings.aspectRatio}`);
  }

  // User's additional prompt (appended, not replacing)
  if (settings.userPrompt?.trim()) {
    parts.push(settings.userPrompt.trim());
  }

  // If we have inspiration bubbles, mention them
  if (settings.generalInspiration?.length) {
    parts.push(`Using ${settings.generalInspiration.length} inspiration bubble(s)`);
  }

  return parts.join('. ');
}
