export {
  AI_MODELS,
  AVAILABLE_IMAGE_MODELS,
  AVAILABLE_TEXT_MODELS,
  DEFAULT_AI_MODEL_CONFIG,
  OPTIMIZATION_DEFAULTS,
  COST_ESTIMATES,
  ERROR_MESSAGES,
  MATERIAL_KEYWORDS,
  COLOR_KEYWORDS,
  STYLE_MAP,
  getModelsForTask,
  getModelsWithReferenceSupport,
  getModelsWithEditingSupport,
  getModelsForGeneration,
  selectBestModel,
  getUpgradeRecommendation,
  getModelById,
  modelSupportsCapability,
} from 'visualizer-ai/client';

export type {
  ModelTask,
  ModelApiType,
  ModelTier,
  ModelCapabilities,
  AIModelOption,
  TextModelOption,
  ModelSelectionContext,
  AIModelConfig,
} from 'visualizer-ai/client';
