#!/bin/bash

# dev-ngrok.sh - Start development server with ngrok tunnel
# This script:
# 1. Starts ngrok tunnel in the background
# 2. Waits for ngrok to be ready and gets the public URL
# 3. Sets BETTER_AUTH_URL, NEXT_PUBLIC_BETTER_AUTH_URL, NEXT_PUBLIC_APP_URL
# 4. Starts the Next.js dev server

set -e

# Configuration
PORT="${PORT:-3000}"
NGROK_REGION="${NGROK_REGION:-us}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}   Development Server with ngrok       ${NC}"
echo -e "${BLUE}========================================${NC}"

# Function to cleanup on exit
cleanup() {
  echo -e "\n${YELLOW}Cleaning up...${NC}"
  if [ ! -z "$NGROK_PID" ]; then
    kill $NGROK_PID 2>/dev/null || true
  fi
  exit 0
}

trap cleanup SIGINT SIGTERM

# Check if ngrok is installed
if ! command -v ngrok &> /dev/null; then
  echo -e "${RED}Error: ngrok is not installed${NC}"
  echo "Install it with: brew install ngrok"
  exit 1
fi

# Check if port is already in use
if lsof -i :$PORT &> /dev/null; then
  echo -e "${YELLOW}Warning: Port $PORT is already in use${NC}"
  read -p "Do you want to use a different port? (y/n): " answer
  if [[ "$answer" =~ ^[Yy]$ ]]; then
    read -p "Enter port number: " PORT
  else
    echo -e "${RED}Exiting...${NC}"
    exit 1
  fi
fi

# Start ngrok in background
echo -e "${BLUE}Starting ngrok tunnel on port $PORT...${NC}"
ngrok http $PORT --log=stdout > /tmp/ngrok.log 2>&1 &
NGROK_PID=$!

# Wait for ngrok to start and get the URL
echo -e "${YELLOW}Waiting for ngrok to initialize...${NC}"
NGROK_URL=""
MAX_ATTEMPTS=30
ATTEMPT=0

while [ -z "$NGROK_URL" ] && [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
  sleep 1
  ATTEMPT=$((ATTEMPT + 1))

  # Try to get URL from ngrok API
  NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels 2>/dev/null | grep -o '"public_url":"https://[^"]*' | head -1 | cut -d'"' -f4 || true)

  if [ -z "$NGROK_URL" ]; then
    echo -ne "\rWaiting for ngrok... ($ATTEMPT/$MAX_ATTEMPTS)"
  fi
done
echo ""

if [ -z "$NGROK_URL" ]; then
  echo -e "${RED}Error: Failed to get ngrok URL${NC}"
  echo "Check ngrok logs: cat /tmp/ngrok.log"
  cleanup
  exit 1
fi

echo -e "${GREEN}ngrok tunnel established!${NC}"
echo -e "${GREEN}Public URL: ${NGROK_URL}${NC}"
echo ""

# Export environment variables
export BETTER_AUTH_URL="${NGROK_URL}/"
export NEXT_PUBLIC_BETTER_AUTH_URL="${NGROK_URL}/"
export NEXT_PUBLIC_APP_URL="${NGROK_URL}"

echo -e "${BLUE}Environment variables set:${NC}"
echo -e "  BETTER_AUTH_URL=${BETTER_AUTH_URL}"
echo -e "  NEXT_PUBLIC_BETTER_AUTH_URL=${NEXT_PUBLIC_BETTER_AUTH_URL}"
echo -e "  NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}"
echo ""

# Create a temporary env file for reference
ENV_OVERRIDE_FILE=".env.ngrok"
cat > $ENV_OVERRIDE_FILE << EOF
# Auto-generated by dev-ngrok.sh - DO NOT COMMIT
# Generated at: $(date)
# ngrok URL: ${NGROK_URL}

BETTER_AUTH_URL=${NGROK_URL}/
NEXT_PUBLIC_BETTER_AUTH_URL=${NGROK_URL}/
NEXT_PUBLIC_APP_URL=${NGROK_URL}
EOF

echo -e "${YELLOW}Created $ENV_OVERRIDE_FILE with ngrok URLs${NC}"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}Starting Next.js development server...${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${YELLOW}Access your app at: ${NGROK_URL}${NC}"
echo -e "${YELLOW}ngrok dashboard: http://127.0.0.1:4040${NC}"
echo ""

# Start Next.js dev server with the port
PORT=$PORT yarn dev
